/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/BaseButton.vue')['default']
    BaseGrouCard: typeof import('./components/BaseGrouCard.vue')['default']
    BaseGroupCard: typeof import('./components/BaseGroupCard.vue')['default']
    BaseGroupCardContent: typeof import('./components/BaseGroupCardContent.vue')['default']
    BaseGroupCardCotent: typeof import('./components/BaseGroupCardCotent.vue')['default']
    BaseInput: typeof import('./components/BaseInput.vue')['default']
    BaseModal: typeof import('./components/BaseModal.vue')['default']
    BaseNavItem: typeof import('./components/BaseNavItem.vue')['default']
    Calendar: typeof import('./components/Calendar.vue')['default']
    Chart: typeof import('./components/Chart.vue')['default']
    EmailVerifyForm: typeof import('./components/forms/EmailVerifyForm.vue')['default']
    IconLineMdLoadingTwotoneLoop: typeof import('~icons/line-md/loading-twotone-loop')['default']
    IconMaterialSymbolsAccountCircleOutline: typeof import('~icons/material-symbols/account-circle-outline')['default']
    IconMaterialSymbolsArrowBackIosRounded: typeof import('~icons/material-symbols/arrow-back-ios-rounded')['default']
    IconMaterialSymbolsExitToAppRounded: typeof import('~icons/material-symbols/exit-to-app-rounded')['default']
    IconMaterialSymbolsGroupOutlineRounded: typeof import('~icons/material-symbols/group-outline-rounded')['default']
    IconMaterialSymbolsGroupRounded: typeof import('~icons/material-symbols/group-rounded')['default']
    IconMaterialSymbolsHelpOutlineRounded: typeof import('~icons/material-symbols/help-outline-rounded')['default']
    IconMaterialSymbolsHouseArrowBackIosRounded: typeof import('~icons/material-symbols/house-arrow-back-ios-rounded')['default']
    IconMaterialSymbolsHouseOutlineRounded: typeof import('~icons/material-symbols/house-outline-rounded')['default']
    IconMaterialSymbolsSetting: typeof import('~icons/material-symbols/setting')['default']
    IconMaterialSymbolsSettings: typeof import('~icons/material-symbols/settings')['default']
    IconMaterialSymbolsStetting: typeof import('~icons/material-symbols/stetting')['default']
    IconMaterialSymbolsStettings: typeof import('~icons/material-symbols/stettings')['default']
    IconMaterialSymbolsVerifiedOutlineRounded: typeof import('~icons/material-symbols/verified-outline-rounded')['default']
    LoginForm: typeof import('./components/forms/LoginForm.vue')['default']
    MyGroup: typeof import('./components/MyGroup.vue')['default']
    MyPage: typeof import('./components/MyPage.vue')['default']
    PasswordResetForm: typeof import('./components/forms/PasswordResetForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignForm: typeof import('./components/forms/SignForm.vue')['default']
  }
}
